server:
  applicationConnectors:
    - type: http
      port: 17000
  adminConnectors:
    - type: http
      port: 17001

elasticsearch:
  hosts: localhost
  cluster: foxtrot
  tableNamePrefix: foxtrot
  getQueryTimeout: 10000

serviceDiscovery:
  namespace: phonepe
  environment: local
  zookeeper: localhost:2181
  publishedHost: 127.0.0.1
  publishedPort: 8080

riemann:
  host: local
  port: 5555
  prefix: phonepe.local.foxtrot
  pollingInterval: 30
  tags:
    - foxtrot

hbase:
  secure : false
  tableName: foxtrot
  hbaseZookeeperQuorum: localhost
  hbaseZookeeperClientPort: 2181
  seggregatedTablePrefix: foxtrot-
  hbaseZookeeperZnodeParent: /hbase-unsecure

cluster:
  name: foxtrot
  discovery:
    type: foxtrot_simple
    disableMulticast: true
    members: ["localhost:5701"]

cacheConfig:
  maxIdleSeconds: 15
  timeToLiveSeconds: 15

logging:
  level: INFO

cardinality:
  enabled: true
  batchSize: 10
  active: true
  interval: 86400
  initialDelay: 6
  maxCardinality: 20000

esIndexOptimizationConfig:
  active: true
  interval: 86400
  initialDelay: 6

consoleHistoryConfig:
  active: true
  interval: 86400
  initialDelay: 10

deletionconfig:
  active: false
  interval: 86400
  initialdelay: 60

emailConfig:
  from: noreply@phonepe.com
  host: ops-jump001.phonepe.nm1
  port: 25
  user: AKIAJLCWHAOEDK4ZDOGQ
  password: AgjCxNI68hrnj6bIzuJCiZBlDXW+TioRoU11++Yx97
  url: /

swagger:
  resourcePackage: com.flipkart.foxtrot.server.resources
  title: Foxtrot
  description: A store abstraction and analytics system for real-time event data.
  uriPrefix: "/foxtrot"

gandalfConfig:
  httpConfig:
    usingZookeeper: false
    host: gandalf.traefik.stg.phonepe.com
    port: 80
    serviceName: gandalf
    environment: stage
    connections: 10
    idleTimeOutSeconds: 30
  authConfig:
    clientId: echo
    clientKey:  1234
    namespace:  echo
  permissionCacheConfig:
    ttlSeconds: 900
    enabled: true

primerBundleConfiguration:
  enabled: true
  authTypesEnabled:
    CONFIG: false
    ANNOTATION: true
  endpoint:
    type: simple
    host: primer.traefik.stg.phonepe.com
    port: 80
  cacheExpiry: 60
  cacheMaxSize: 100000
  clockSkew: 60
  prefix: Bearer
  privateKey: TwhjV5ujkvb41frpmqCve7ZfhqwSDMqOXe01DeDIsb2xCrW4bwfFnax9bi2uC9Kn

restrictAccess: false

segregationConfiguration:
  tableEventConfigs:
    phonepe_consumer_app_android:
      phonepe_consumer_app_android_app_loaded:
        - APP_LOADED
  ignoredEventConfigs:
    phonepe_consumer_app_android:
      - ACTIVITY_VISITED
