server:
  applicationConnectors:
    - type: http
      port: 17000
  adminConnectors:
    - type: http
      port: 17001

elasticsearch:
  hosts:
  - localhost
  cluster: foxtrot
  tableNamePrefix: foxtrot
  getQueryTimeout: 10000

hbase:
  secure : false
  tableName: foxtrot
  hbaseZookeeperQuorum: localhost
  hbaseZookeeperClientPort: 2181

cluster:
  name: foxtrot
  discovery:
    type: foxtrot_simple
    disableMulticast: true
    members: ["localhost:5701"]

cacheConfig:
  maxIdleSeconds: 15
  timeToLiveSeconds: 15

logging:
  level: INFO

cardinality:
  enabled: true
  batchSize: 10
  active: true
  interval: 86400
  initialDelay: 6
  maxCardinality: 20000

esIndexOptimizationConfig:
  active: true
  interval: 86400
  initialDelay: 6

deletionconfig:
  active: false
  interval: 86400
  initialdelay: 60
  
  logRotationFileConfig:
    minIndex: 0
    maxIndex: 3
    maxFileSize: 1MB
    filePattern: /var/log/flipkart/foxtrot-server/server-%i.log.gz
