server:
  applicationConnectors:
    - type: http
      port: 17000
  adminConnectors:
    - type: http
      port: 17001

elasticsearch:
  hosts:
  - stg-els601.phonepe.nm2
  cluster: foxtrot
  tableNamePrefix: foxtrot
  getQueryTimeout: 10000
  connectionType: HTTP
  port: 9200

hbase:
  secure : false
  tableName: foxtrot
  hbaseZookeeperQuorum: stg-dwhxenial002-stg-cloud005.phonepe.nm2:2181
  hbaseZookeeperClientPort: 2181
  seggregatedTablePrefix: foxtrot-
  hbaseZookeeperZnodeParent: /hbase-test

cluster:
  name: foxtrot
  discovery:
    type: foxtrot_simple
    disableMulticast: true
    members: ["localhost:5701"]

cacheConfig:
  maxIdleSeconds: 15
  timeToLiveSeconds: 15

logging:
  level: INFO

cardinality:
  enabled: true
  batchSize: 10
  active: true
  interval: 86400
  initialDelay: 6
  maxCardinality: 20000

elasticsearchTuningConfig:
  precisionThreshold: 500
  aggregationSize: 10000
  scrollTimeInSeconds: 120
  documentsLimitAllowed: 10000

esIndexOptimizationConfig:
  active: true
  interval: 86400
  initialDelay: 6

consoleHistoryConfig:
  active: true
  interval: 86400
  initialDelay: 10

deletionconfig:
  active: false
  interval: 86400
  initialdelay: 60

sessionCleanupConfig:
  active: true
  interval: 86400
  initialDelay: 10

auth:
  enabled: false
  jwt:
    issuerId: foxtrot-server
    privateKey: ${PRIVATE_KEY}
    sessionDuration: 15d

  provider:
    type: OAUTH_GOOGLE
    clientId: ${GOOGLE_CLIENT_ID}
    clientSecret: ${GOOGLE_CLIENT_SECRET}
    server: ${GOOGLE_CALLBACK_HOST_PORT}
    secureEndpoint: false